[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000
viaIR = true
solc = "0.8.20"

remappings = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options